_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 3
    BATCH_SIZE_PER_IMAGE: 128
#OUTPUT_DIR: 
DATASETS:
  TRAIN: ("train",)
  TEST: ()
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 10
  IMS_PER_BATCH: 1
  BASE_LR: 0.001
  WARMUP_ITERS: 1000